apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-nginx-conf
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  nginx.conf: |
    server {
        listen 80 default_server;
        set $environment kubernetes;
        set $root_folder /usr/share/nginx/www;
        root $root_folder;

        # ssl certificates
        #ssl_certificate     certs/prod/star.bizzabo.com.chain.crt;
        #ssl_certificate_key certs/prod/star.bizzabo.com.key;

        proxy_buffer_size 64k;
        proxy_buffers 4 128k;
        proxy_busy_buffers_size 128k;

        try_files $uri $uri/ /index.html =404;


        set_real_ip_from  0.0.0.0/0;
        real_ip_header    X-Forwarded-For;

        location / {
            expires -1;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;

            proxy_pass http://127.0.0.1:{{ .Values.service.nodePort }}/;
            proxy_redirect off;
        }

        location /nginx_status {
          stub_status  on;
          access_log   off;
        }

        location = /health {
            access_log off;
            default_type text/plain;
            return 200 "OK";
        }

        location ~* ^/static/.+\.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|pdf|txt|tar|wav|bmp|rtf|js|flv|swf|html|htm|eot|woff|ttf|otf|svg|map|hbs|json)$ {
            root $root_folder/static;
        }
    }
