apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-server-conf
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    port: {{ .Values.service.nodePort }}
    webloginEncryptionKey: {{ .Values.webloginEncryptionKey | default .Values.global.webloginEncryptionKey }}
      public:
        apiServer: {{ template "common.bizzabo.api_server.url" . }}
        dashboardUrl: {{ template "common.bizzabo.webdashboard.url" . }}
        hostUrl: {{ template "common.bizzabo.<%= serviceName %>.url" . }}

