apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-server-conf
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    env: {{ .Values.env | default .Values.global.env }}
    apiServer: {{ template "common.bizzabo.api_server.url" . }}
    port: {{ .Values.service.nodePort }}
