version: 2.1

orbs:
  npm: bizzabo/npm@1.1.0
  docker: bizzabo/docker@1.2.0
  kubernetes: bizzabo/kubernetes@1.3.0

executors:
  js:
    docker:
      - image: circleci/node:lts-stretch

workflows:
  publish-to-dev:
    jobs:
      - npm/checkout_build_test:
          name: Checkout Build Test
          context: dev
          additional-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - Dockerfile
                  - app/dist
                  - package.json
                  - server
                  - next.config.js
                  - node_modules
          filters:
            branches:
              ignore:
                - master

#      - publish-test-results:
#          name: Upload Tests
#          requires:
#            - Checkout Build Test
#
      - docker/build_publish_as_candidate:
          name: Publish Project
          context: dev
          checkout: false
          attach-workspace: true
          repo: <%= serviceName %>
          tag: ${CIRCLE_SHA1:0:7}
          requires:
            - Checkout Build Test

#      - kubernetes/deploy_to_dev_k8s:
#          name: Deploy To Dev
#          context: dev
#          kops-cluster-endpoint: blue.dev.bizzabo.com
#          kops-state-store: s3://bizzabo-kubernetes-state-store
#          helm-assembly-repo-url: git@github.com:bizzabo/helm-assembly.git
#          helm-chart-path: helm-assembly/charts/bizzabo
#          helm-values-path: helm-assembly/charts/bizzabo/values.yaml
#          requires:
#            - Publish Project